### ISSUE TITLE
I think 2020 broke some time....things

### ISSUE THREAD

**Issue by cogphn** [keydet89/RegRipper2.8#60]
run recentdocs_tln before 2020 - dates show up run it after - dates do not show up

**Comment by keydet89** [comment]
Is this the same hive file in both cases?  

Can you share it?

keydet89 at yahoo dot com

**Comment by cogphn** [comment]
It's the same NTUSER.DAT file - I tested with a few and the behavior seems consistent. Once I set the clock back to 2019 the dates show up in the output. Sending you a safe sample

**Comment by wschaeferB** [comment]
Encountering something similar where dates extracted from the system such as the usb device dates extracted by usb.pl are showing up as [Thu Jan  1 00:00:00 1970] since it 1/1/2020 and were showing up correctly as dates like [Fri Jan 20 17:10:09 2012] up through 12/31/2019. While there are some sections such as the sub appXP32Bit code in shimcache.pl which are still writing dates which make sense, the vast majority of the dates printed in the output have become 1/1/1970.

**Comment by wschaeferB** [comment]
Seems like it is an issue either needing an updated version of perl according to this 
https://pandorafms.com/blog/2020-perl/

**Comment by keydet89** [comment]
yep, you're not the first one to say something...I've got a fix I'll be putting out this weekend.

Thanks.

**Comment by keydet89** [comment]
Updates posted to Github.  Thanks!
